routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')
     ->namespace('Admin')
     ->name('admin.')
     ->middleware(['auth.admin', 'role.check', 'first.access', 'term.check'])
     ->group(function () {

         Route::namespace('Dashboard')->group(function () {
             Route::name('dashboard.index')->get('/', 'DashboardController@index');

             Route::prefix('financial')->name('financial.')->group(function () {
                 Route::name('index')->get('/', 'FinancialController@index');
                 Route::get('/income', 'FinancialController@income');
                 Route::get('/outcome', 'FinancialController@outcome');
                 Route::get('/active-students', 'FinancialController@activeStudents');
                 Route::get('/registrations', 'FinancialController@registrations');
                 Route::get('/billing-summary', 'FinancialController@billingSummary');
                 Route::get('/billing-per-payment-type', 'FinancialController@billingPerPaymentType');
                 Route::get('/students-by-status', 'FinancialController@studentsByStatus');
             });

             Route::prefix('academic')->name('academic.')->group(function () {
                 Route::name('index')->get('/', 'AcademicController@index');
                 Route::get('/students-per-sex', 'AcademicController@studentsPerSex');
                 Route::get('/students-per-age-categories', 'AcademicController@studentsPerAgeCategories');
                 Route::get('/students-per-bands', 'AcademicController@studentsPerBands');
             });
         });

         Route::namespace('TrainingCenter')->group(function () {
             Route::resource('students', 'StudentController', ['except' => 'show']);
             Route::resource('age-categories', 'AgeCategoryController', ['except' => 'show']);
             Route::resource('origins', 'OriginController', ['except' => 'show']);
             Route::resource('guardians', 'GuardianController', ['except' => 'show']);
             Route::resource('teachers', 'TeacherController', ['except' => 'show']);
             Route::resource('bands', 'BandController', ['except' => 'show']);
             Route::resource('modalities', 'ModalityController', ['except' => 'show']);

             Route::resource('classrooms', 'ClassroomController');

             Route::prefix('classrooms')->name('classrooms.')->group(function () {
                 Route::resource('{classroom}/frequencies', 'FrequencyController');
                 Route::name('activate')->get('/activate/{classroom}', 'ClassroomController@activate');
                 Route::name('deactivate')->get('/deactivate/{classroom}', 'ClassroomController@deactivate');
             });

             Route::resource('classrooms-teachers', 'ClassroomTeacherController');

             Route::prefix('classrooms-teachers')->name('classrooms-teachers.')->group(function() {
                Route::name('add-teacher')->post('/add-teacher', 'ClassroomTeacherController@addTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
             });

             Route::name('students.')->prefix('students')->group(function () {
                 Route::name('export')->get('/export', 'StudentController@export');
                 Route::resource('attachments', 'AttachmentController', ['only' => ['show', 'update']]);

                 Route::resource('{registration}/graduations', 'GraduationController', ['except' => 'show']);
                 Route::resource('{registration}/installments', 'InstallmentController', ['except' => 'show']);
                 Route::resource('{registration}/issues', 'IssueController', ['only' => 'index']);

                 Route::name('skip-check')->post('/skip-check/{registration}', 'StudentController@skipcheck');
                 Route::name('graduations.print')->get('{registration}/print/{graduation}', 'GraduationController@print');
                 Route::name('deactivate-registration')->post('/deactivate-registration/{registration}', 'StudentController@deactivateRegistration');
                 Route::name('reactivate-registration')->get('/reactivate-registration/{registration}', 'StudentController@reactivateRegistration');
            });

            Route::name('new-registration.')->prefix('new-registration')->group(function () {
                Route::name('index')->get('/index', 'NewRegistrationController@index');
                Route::name('guardian')->get('/{student}/guardian', 'NewRegistrationController@guardian');
                Route::name('registration')->get('/{student}/registration', 'NewRegistrationController@registration');
                Route::name('financial')->get('/{student}/financial', 'NewRegistrationController@financial');
                Route::name('graduation')->get('/{student}/graduation', 'NewRegistrationController@graduation');

                Route::name('save-student')->post('/save-student', 'NewRegistrationController@saveStudent');
                Route::name('save-guardian')->post('/{student}/save-guardian', 'NewRegistrationController@saveGuardian');
                Route::name('save-registration')->post('/{student}/save-registration', 'NewRegistrationController@saveRegistration');
                Route::name('save-financial')->post('/{student}/save-financial', 'NewRegistrationController@saveFinancial');
                Route::name('save-graduation')->post('/{student}/save-graduation', 'NewRegistrationController@saveGraduation');
            });
         });

         Route::namespace('Auth')->prefix('users')->group(function () {
             Route::resource('permissions', 'PermissionController', ['except' => 'show']);
             Route::resource('roles', 'RoleController', ['except' => 'show']);

             Route::name('users.sendEmail')->get('/resend-confirmation/{user}', 'UserController@sendEmail');
             Route::name('users.activate')->get('/activate/{user}', 'UserController@activate');
             Route::name('users.deactivate')->get('/deactivate/{user}', 'UserController@deactivate');
         });

         Route::namespace('Finances')->group(function () {
             Route::resource('balance-records', 'BalanceRecordController', ['except' => 'show']);
             Route::resource('monthly-charge', 'MonthlyChargeController', ['only' => 'store']);
         });

         Route::namespace('Juno')->prefix('juno')->group(function() {
             Route::resource('transfer', 'TransferController', ['only' => ['index', 'store']]);
             Route::resource('split', 'SplitReportController', ['only' => ['index']]);
             Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'store']]);
         });

         Route::name('juno.')->prefix('juno')->group(function() {
            Route::name('cancel')->prefix('cancel')->post('/cancel/{invoice}', 'Juno\InvoiceController@cancel');
            Route::name('manual-payment')->prefix('manual-payment')->post('/manual-payment/{invoice}', 'Juno\InvoiceController@manulPayment');
        });

         Route::namespace('Reports')->group(function(){
             Route::prefix('qualifications')->name('qualifications.')->group(function() {
                 Route::name('index')->get('/', 'QualificationController@index');
                 Route::name('print')->get('/print', 'QualificationController@print');
             });

              Route::prefix('reports')->name('reports.')->group(function () {
                 Route::name('balance')->get('/balance', 'BalanceController@index');
                 Route::name('overdue')->get('/overdue', 'OverdueController@index');
                 Route::name('resend-overdues')->post('/resend-overdues', 'OverdueController@resend');
                 Route::name('class-billing')->get('/class-billing', 'BillingPerClassController@index');
                 Route::name('annual-summary')->get('/annual-summary', 'AnnualSummaryController@index');
              });
         });

         Route::resource('persons', 'PersonController', ['only' => 'show']);
         Route::resource('messages', 'MessageController');
         Route::resource('users', 'Auth\UserController', ['except' => 'show']);
         Route::resource('audits', 'AuditController', ['only' => ['index', 'show']]);
         Route::resource('subsidiaries', 'SubsidiaryController', ['except' => 'show']);

         Route::prefix('subsidiaries')->name('subsidiaries.')->group(function(){
             Route::name('documents.index')->get('{id}/documents', 'DocumentController@index');
             Route::name('documents.store')->post('{id}/documents/store', 'DocumentController@store');
         });

         Route::prefix('settings')->name('settings.')->group(function (){
             Route::name('edit')->get('/edit', 'SettingController@edit');
             Route::name('update')->put('/update', 'SettingController@update');
         });

         Route::prefix('users')->name('users.')->group(function () {
            Route::name('term')->get('/term', 'UserTermController@index');
            Route::name('accept-term')->post('/accept-term', 'UserTermController@accept');
         });
     });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest.admin')->group(function () {

    //Auto login
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    Route::namespace('Auth\Sessions')->group(function () {

        Route::get('/', 'SessionController@showLoginForm');
        Route::name('login')->get('/login', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->get('/acessar', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->post('/acessar', 'SessionController@login');

        // Reset Password
        Route::name('auth.password.forgot')->get('/esqueci-minha-senha', 'ForgotPasswordController@showLinkRequestForm');
        Route::name('auth.password.processForgot')->post('/esqueci-minha-senha', 'ForgotPasswordController@sendResetLinkEmail');
        Route::name('auth.password.reset')->get('/cadastrar-senha/{token}/{email}', 'ResetPasswordController@showResetForm');
        Route::name('auth.password.processReset')->post('/cadastrar-senha', 'ResetPasswordController@reset');

        // First access
        Route::name('auth.activation.create')->get('/primeiro-acesso/{activation}', 'ActivationController@showActivationForm');
        Route::name('auth.activation.processCreate')->post('/primeiro-acesso/{token}', 'ActivationController@store');
    });
});

// Logout
Route::middleware('auth.admin')->group(function() {
    Route::name('auth.session.logout')->get('/sair', 'Auth\Sessions\SessionController@logout');
    Route::name('core.notifications.destroy')->delete('/excluir/{notification}', 'Core\NotificationController@destroy');
    Route::name('core.notifications.read')->put('/{notification}', 'Core\NotificationController@update');
});

resources/views/layouts/common/_favicons.blade.php
<link rel="icon" href="{{ asset('img/favicons/favicon.ico') }}" type="image/x-icon">
<link rel="icon" sizes="16x16" href="{{ asset('img/favicons/favicon-16x16.png') }}" type="image/png">
<link rel="icon" sizes="32x32" href="{{ asset('img/favicons/favicon-32x32.png') }}" type="image/png">

<!-- icon in the highest resolution we need it for -->
<link rel="icon" sizes="192x192" href="{{ asset('img/favicons/android-chrome-192x192.png') }}">

<!-- reuse same icon for Safari -->
<link rel="apple-touch-icon" href="{{ asset('img/favicons/apple-touch-icon.png') }}">

<!-- multiple icons for IE -->
<meta name="msapplication-square70x70logo" content="{{ asset('img/favicons/mstile-70x70.png') }}">
<meta name="msapplication-square150x150logo" content="{{ asset('img/favicons/mstile-150x150.png') }}">
<meta name="msapplication-wide310x150logo" content="{{ asset('img/favicons/mstile-310x150.png') }}">

resources/views/layouts/common/_nav-member.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <a href="{{ route("$currentAccess.dashboard.index") }}"
       class="navbar-brand sidebar-gone-hide">
        <img height="50" width="50" src="{{ asset( $avatar ) }}">
        <span class="text-dark"></span>
    </a>
    <div class="navbar-nav">
    </div>
    <div class="nav-collapse">
    </div>
    <form class="form-inline ml-auto">
    </form>
    <ul class="navbar-nav navbar-right">

        @include('layouts.common._notifications', ['color' => 'dark'])

        <li class="dropdown">
            <a href="#" data-toggle="dropdown"
               class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ auth()->user()->avatarUrl }}"
                     class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block text-dark">
                    {{ auth()->user()->nickname }}
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">

                @include('layouts.common._roles')

                <div class="dropdown-divider"></div>
                <a href="{{ route("$currentAccess.accounts.edit") }}"
                   class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Perfil
                </a>

                @if(!empty(auth()->user()->teacher()->first()))
                    <div class="dropdown-divider"></div>
                    <a href="{{ route("teachers.financial.balance") }}"
                    class="dropdown-item has-icon">
                        <i class="fas fa-wallet lga"></i> Saldo
                    </a>

                    <div class="dropdown-divider"></div>
                    <a href="{{ route("teachers.financial.yield") }}"
                    class="dropdown-item has-icon">
                        <i class="fas fa-cash-register lga"></i> Rendimentos
                    </a>
                @endif

                <div class="dropdown-divider"></div>
                <a href="{{ route('auth.session.logout') }}"
                   class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> Sair
                </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/common/_notifications.blade.php
<li class="dropdown dropdown-list-toggle">
    <a href="#"
       data-toggle="dropdown"
       class="nav-link notification-toggle nav-link-lg {{ count(auth()->user()->notifications) ? 'beep' : '' }}">
        <i class="fas fa-bell text-{{ $color ?? 'white' }}"></i>
    </a>
    <div class="dropdown-menu dropdown-list dropdown-menu-right shadow rounded">
        <div class="dropdown-header bg-primary text-white">Notificações</div>
        <div class="dropdown-list-content dropdown-list-icons">
            @foreach(auth()->user()->notifications as $notification)
                <div class="dropdown-item dropdown-item-unread notification {{ $notification->read() ? 'bg-light' : '' }}">
                    <div class="dropdown-item-icon bg-primary">
                        <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                    <div class="dropdown-item-desc w-100">
                        <div class="time text-primary">{{ $notification->data['subject'] }}
                            <a href="#"
                               class="js-notification-delete"
                               data-link="{{ route('core.notifications.destroy', ['notification' => $notification->id]) }}">
                                <i class="fas fa-times float-right"></i></a>
                        </div>
                        <a href="#"
                           class="js-notification-redirect"
                           data-link="{{ $notification->data['link'] }}"
                           data-read-link="{{ route('core.notifications.read', ['notification' => $notification->id]) }}">
                            {{ $notification->data['message'] }}
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="dropdown-footer text-center"><p></p>
        </div>
    </div>
</li>

resources/views/layouts/common/_roles.blade.php
<div class="dropdown-title" style="padding: 1px 20px;">
    <b>Visões</b>
</div>
<div class="dropdown-divider"></div>
@foreach(auth()->user()->roles as $role)
    @switch($role->name)
        @case('root')
        @case('gestor')
        <a href="{{ route('admin.dashboard.index') }}"
           class="dropdown-item has-icon"><i
                    class="far fa-circle"></i>{{ $role->details }}
        </a>
        @break
        @case('aluno')
        <a href="{{ route('students.dashboard.index') }}"
           class="dropdown-item has-icon"><i
                    class="far fa-circle"></i>{{ $role->details }}
        </a>
        @break
        @case('professor')
        <a href="{{ route('teachers.dashboard.index') }}"
           class="dropdown-item has-icon"><i
                    class="far fa-circle"></i>{{ $role->details }}
        </a>
        @break
        @case('responsavel')
        <a href="{{ route('guardians.dashboard.index') }}"
           class="dropdown-item has-icon"><i
                    class="far fa-circle"></i>{{ $role->details }}
        </a>
        @break
    @endswitch
@endforeach

resources/views/layouts/common/_toast.blade.php
@if(Session::has('toasts'))
	<script type="text/javascript">
		@foreach(Session::get('toasts') as $toast)
		iziToast.{{ $toast['level'] }} ({
			title: "{{ $toast['title'] }}",
			message: "{{ $toast['message'] }}",
			position: 'topRight'
        });
		@endforeach
	</script>
@endif