routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')
     ->namespace('Admin')
     ->name('admin.')
     ->middleware(['auth.admin', 'role.check', 'first.access', 'term.check'])
     ->group(function () {

         Route::namespace('Dashboard')->group(function () {
             Route::name('dashboard.index')->get('/', 'DashboardController@index');

             Route::prefix('financial')->name('financial.')->group(function () {
                 Route::name('index')->get('/', 'FinancialController@index');
                 Route::get('/income', 'FinancialController@income');
                 Route::get('/outcome', 'FinancialController@outcome');
                 Route::get('/active-students', 'FinancialController@activeStudents');
                 Route::get('/registrations', 'FinancialController@registrations');
                 Route::get('/billing-summary', 'FinancialController@billingSummary');
                 Route::get('/billing-per-payment-type', 'FinancialController@billingPerPaymentType');
                 Route::get('/students-by-status', 'FinancialController@studentsByStatus');
             });

             Route::prefix('academic')->name('academic.')->group(function () {
                 Route::name('index')->get('/', 'AcademicController@index');
                 Route::get('/students-per-sex', 'AcademicController@studentsPerSex');
                 Route::get('/students-per-age-categories', 'AcademicController@studentsPerAgeCategories');
                 Route::get('/students-per-bands', 'AcademicController@studentsPerBands');
             });
         });

         Route::namespace('TrainingCenter')->group(function () {
             Route::resource('students', 'StudentController', ['except' => 'show']);
             Route::resource('age-categories', 'AgeCategoryController', ['except' => 'show']);
             Route::resource('origins', 'OriginController', ['except' => 'show']);
             Route::resource('guardians', 'GuardianController', ['except' => 'show']);
             Route::resource('teachers', 'TeacherController', ['except' => 'show']);
             Route::resource('bands', 'BandController', ['except' => 'show']);
             Route::resource('modalities', 'ModalityController', ['except' => 'show']);

             Route::resource('classrooms', 'ClassroomController');

             Route::prefix('classrooms')->name('classrooms.')->group(function () {
                 Route::resource('{classroom}/frequencies', 'FrequencyController');
                 Route::name('activate')->get('/activate/{classroom}', 'ClassroomController@activate');
                 Route::name('deactivate')->get('/deactivate/{classroom}', 'ClassroomController@deactivate');
             });

             Route::resource('classrooms-teachers', 'ClassroomTeacherController');

             Route::prefix('classrooms-teachers')->name('classrooms-teachers.')->group(function() {
                Route::name('add-teacher')->post('/add-teacher', 'ClassroomTeacherController@addTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
             });

             Route::name('students.')->prefix('students')->group(function () {
                 Route::name('export')->get('/export', 'StudentController@export');
                 Route::resource('attachments', 'AttachmentController', ['only' => ['show', 'update']]);

                 Route::resource('{registration}/graduations', 'GraduationController', ['except' => 'show']);
                 Route::resource('{registration}/installments', 'InstallmentController', ['except' => 'show']);
                 Route::resource('{registration}/issues', 'IssueController', ['only' => 'index']);

                 Route::name('skip-check')->post('/skip-check/{registration}', 'StudentController@skipcheck');
                 Route::name('graduations.print')->get('{registration}/print/{graduation}', 'GraduationController@print');
                 Route::name('deactivate-registration')->post('/deactivate-registration/{registration}', 'StudentController@deactivateRegistration');
                 Route::name('reactivate-registration')->get('/reactivate-registration/{registration}', 'StudentController@reactivateRegistration');
            });

            Route::name('new-registration.')->prefix('new-registration')->group(function () {
                Route::name('index')->get('/index', 'NewRegistrationController@index');
                Route::name('guardian')->get('/{student}/guardian', 'NewRegistrationController@guardian');
                Route::name('registration')->get('/{student}/registration', 'NewRegistrationController@registration');
                Route::name('financial')->get('/{student}/financial', 'NewRegistrationController@financial');
                Route::name('graduation')->get('/{student}/graduation', 'NewRegistrationController@graduation');

                Route::name('save-student')->post('/save-student', 'NewRegistrationController@saveStudent');
                Route::name('save-guardian')->post('/{student}/save-guardian', 'NewRegistrationController@saveGuardian');
                Route::name('save-registration')->post('/{student}/save-registration', 'NewRegistrationController@saveRegistration');
                Route::name('save-financial')->post('/{student}/save-financial', 'NewRegistrationController@saveFinancial');
                Route::name('save-graduation')->post('/{student}/save-graduation', 'NewRegistrationController@saveGraduation');
            });
         });

         Route::namespace('Auth')->prefix('users')->group(function () {
             Route::resource('permissions', 'PermissionController', ['except' => 'show']);
             Route::resource('roles', 'RoleController', ['except' => 'show']);

             Route::name('users.sendEmail')->get('/resend-confirmation/{user}', 'UserController@sendEmail');
             Route::name('users.activate')->get('/activate/{user}', 'UserController@activate');
             Route::name('users.deactivate')->get('/deactivate/{user}', 'UserController@deactivate');
         });

         Route::namespace('Finances')->group(function () {
             Route::resource('balance-records', 'BalanceRecordController', ['except' => 'show']);
             Route::resource('monthly-charge', 'MonthlyChargeController', ['only' => 'store']);
         });

         Route::namespace('Juno')->prefix('juno')->group(function() {
             Route::resource('transfer', 'TransferController', ['only' => ['index', 'store']]);
             Route::resource('split', 'SplitReportController', ['only' => ['index']]);
             Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'store']]);
         });

         Route::name('juno.')->prefix('juno')->group(function() {
            Route::name('cancel')->prefix('cancel')->post('/cancel/{invoice}', 'Juno\InvoiceController@cancel');
            Route::name('manual-payment')->prefix('manual-payment')->post('/manual-payment/{invoice}', 'Juno\InvoiceController@manulPayment');
        });

         Route::namespace('Reports')->group(function(){
             Route::prefix('qualifications')->name('qualifications.')->group(function() {
                 Route::name('index')->get('/', 'QualificationController@index');
                 Route::name('print')->get('/print', 'QualificationController@print');
             });

              Route::prefix('reports')->name('reports.')->group(function () {
                 Route::name('balance')->get('/balance', 'BalanceController@index');
                 Route::name('overdue')->get('/overdue', 'OverdueController@index');
                 Route::name('resend-overdues')->post('/resend-overdues', 'OverdueController@resend');
                 Route::name('class-billing')->get('/class-billing', 'BillingPerClassController@index');
                 Route::name('annual-summary')->get('/annual-summary', 'AnnualSummaryController@index');
              });
         });

         Route::resource('persons', 'PersonController', ['only' => 'show']);
         Route::resource('messages', 'MessageController');
         Route::resource('users', 'Auth\UserController', ['except' => 'show']);
         Route::resource('audits', 'AuditController', ['only' => ['index', 'show']]);
         Route::resource('subsidiaries', 'SubsidiaryController', ['except' => 'show']);

         Route::prefix('subsidiaries')->name('subsidiaries.')->group(function(){
             Route::name('documents.index')->get('{id}/documents', 'DocumentController@index');
             Route::name('documents.store')->post('{id}/documents/store', 'DocumentController@store');
         });

         Route::prefix('settings')->name('settings.')->group(function (){
             Route::name('edit')->get('/edit', 'SettingController@edit');
             Route::name('update')->put('/update', 'SettingController@update');
         });

         Route::prefix('users')->name('users.')->group(function () {
            Route::name('term')->get('/term', 'UserTermController@index');
            Route::name('accept-term')->post('/accept-term', 'UserTermController@accept');
         });
     });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest.admin')->group(function () {

    //Auto login
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    Route::namespace('Auth\Sessions')->group(function () {

        Route::get('/', 'SessionController@showLoginForm');
        Route::name('login')->get('/login', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->get('/acessar', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->post('/acessar', 'SessionController@login');

        // Reset Password
        Route::name('auth.password.forgot')->get('/esqueci-minha-senha', 'ForgotPasswordController@showLinkRequestForm');
        Route::name('auth.password.processForgot')->post('/esqueci-minha-senha', 'ForgotPasswordController@sendResetLinkEmail');
        Route::name('auth.password.reset')->get('/cadastrar-senha/{token}/{email}', 'ResetPasswordController@showResetForm');
        Route::name('auth.password.processReset')->post('/cadastrar-senha', 'ResetPasswordController@reset');

        // First access
        Route::name('auth.activation.create')->get('/primeiro-acesso/{activation}', 'ActivationController@showActivationForm');
        Route::name('auth.activation.processCreate')->post('/primeiro-acesso/{token}', 'ActivationController@store');
    });
});

// Logout
Route::middleware('auth.admin')->group(function() {
    Route::name('auth.session.logout')->get('/sair', 'Auth\Sessions\SessionController@logout');
    Route::name('core.notifications.destroy')->delete('/excluir/{notification}', 'Core\NotificationController@destroy');
    Route::name('core.notifications.read')->put('/{notification}', 'Core\NotificationController@update');
});

resources/views/admin/subsidiaries/create.blade.php
@extends('layouts.default')

@section('content')

    {!! Form::open(['method' => 'POST', 'novalidate',  'role' => 'form', 'class' => 'form', 'route' => 'admin.subsidiaries.store', 'enctype' => 'multipart/form-data', ]) !!}
    <section class="section">
        <div class="section-header mb-4">
            <div class="section-header-back">
                <a href="{{ route('admin.subsidiaries.index') }}" class="btn btn-icon"
                   title="Voltar">
                    <i class="fas fa-arrow-left"></i>
                </a>
            </div>
            <h1>Nova unidade</h1>
            {!! Breadcrumbs::render('subsidiaries.create') !!}
        </div>

        <div class="clearfix"></div>

        <div class="section-body mt-4">
            <div class="row">
                @include('admin.subsidiaries._form')
            </div>
        </div>
    </section>
    {!! Form::close() !!}

@endsection

resources/views/admin/subsidiaries/edit.blade.php
@extends('layouts.default')

@section('content')

    {!! Form::model($subsidiary, ['method' => 'PUT', 'novalidate', 'role' => 'form', 'class' => 'form', 'route' => ['admin.subsidiaries.update', 'id' => $subsidiary->id], 'enctype' => 'multipart/form-data']) !!}
    <section class="section">
        <div class="section-header mb-4">
            <div class="section-header-back">
                <a href="{{ route('admin.subsidiaries.index') }}" class="btn btn-icon"
                   title="Voltar">
                    <i class="fas fa-arrow-left"></i>
                </a>
            </div>
            <h1>Editar unidade</h1>
            {!! Breadcrumbs::render('subsidiaries.edit', $subsidiary) !!}
        </div>

        <div class="clearfix"></div>

        <div class="section-body mt-4">
            <div class="row">
                @include('admin.subsidiaries._form')
            </div>
        </div>
    </section>
    {!! Form::close() !!}

@endsection

resources/views/admin/subsidiaries/index.blade.php
@extends('layouts.default')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Unidades</h1>
            @can('add_subsidiaries')
                <div class="section-header-button mr-2">
                    <a href="{{ route('admin.subsidiaries.create') }}"
                       class="btn btn-success btn-icon btn-lg"
                       title="Adicionar"> <i class="fas fa-plus"></i> Adicionar</a>
                </div>
            @endcan

            {!! Breadcrumbs::render('subsidiaries.index') !!}
        </div>
        <div class="section-body mt-4">
            <div class="row mt-4">
                <div class="col-12">
                    <h6 class="mb-3">Listagem de unidades cadastradas</h6>
                    <div class="card">
                        <div class="card-body -table mb-0">
                            <div class="table-responsive">
                                <table class="table table-striped overflow mb-0">
                                    <tbody>
                                        <tr class="tr-item td-border">
                                            <th>Nome</th>
                                            <th>Responsável</th>
                                            <th>Telefone</th>
                                            <th></th>
                                        </tr>
                                        @forelse($results as $result)
                                            <tr class="tr-item td-border">
                                                <td class="td-item">{{ $result->name }}</td>
                                                <td class="td-item">{{ $result->manager->nickname }}</td>
                                                <td class="td-item">{{ maskPhone($result->phone) }}</td>
                                                <td class="no-wrap text-right">
                                                    @can('edit_subsidiaries')
                                                        <a href="{{ route('admin.subsidiaries.edit', ['id' => $result->id]) }}"
                                                           data-toggle="tooltip"
                                                           data-placement="top"
                                                           title=""
                                                           data-original-title="Editar">
                                                            <i class="icon far fa-edit lg"></i></a>

                                                        @if(!empty($result->resource_token))
                                                            <a href="{{ route('admin.subsidiaries.documents.index', ['id' => $result->id]) }}"
                                                               data-toggle="tooltip"
                                                               data-placement="top"
                                                               title=""
                                                               data-original-title="Documentos">
                                                                <i class="icon far fa-list-alt lg"></i></a>
                                                        @endif
                                                    @endcan

                                                    @can('delete_subsidiaries')
                                                        <a href="#"
                                                           class="js-confirm-delete"
                                                           data-link="{{ route('admin.subsidiaries.destroy', ['id' => $result->id]) }}"
                                                           data-title="{{ $result->name }}"
                                                           data-toggle="tooltip"
                                                           data-placement="top"
                                                           title=""
                                                           data-original-title="Excluir">
                                                            <i class="icon far fa-trash-alt lg"></i></a>
                                                    @endcan
                                                </td>
                                            </tr>
                                        @empty
                                            <tr class="tr-item td-border">
                                                <td colspan="4"
                                                    class="td-item text-center">
                                                    Nenhum registro encontrado
                                                </td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                    <tfoot>
                                        <tr class="tr-item td-border bg-white">
                                            <td class="td-item">
                                                <b>Total: {!! $results->total() !!}</b>
                                            </td>
                                            <td class="td-item"
                                                colspan="3">
                                                <div class="float-right">{!! $results->render() !!}</div>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection