routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')
     ->namespace('Admin')
     ->name('admin.')
     ->middleware(['auth.admin', 'role.check', 'first.access', 'term.check'])
     ->group(function () {

         Route::namespace('Dashboard')->group(function () {
             Route::name('dashboard.index')->get('/', 'DashboardController@index');

             Route::prefix('financial')->name('financial.')->group(function () {
                 Route::name('index')->get('/', 'FinancialController@index');
                 Route::get('/income', 'FinancialController@income');
                 Route::get('/outcome', 'FinancialController@outcome');
                 Route::get('/active-students', 'FinancialController@activeStudents');
                 Route::get('/registrations', 'FinancialController@registrations');
                 Route::get('/billing-summary', 'FinancialController@billingSummary');
                 Route::get('/billing-per-payment-type', 'FinancialController@billingPerPaymentType');
                 Route::get('/students-by-status', 'FinancialController@studentsByStatus');
             });

             Route::prefix('academic')->name('academic.')->group(function () {
                 Route::name('index')->get('/', 'AcademicController@index');
                 Route::get('/students-per-sex', 'AcademicController@studentsPerSex');
                 Route::get('/students-per-age-categories', 'AcademicController@studentsPerAgeCategories');
                 Route::get('/students-per-bands', 'AcademicController@studentsPerBands');
             });
         });

         Route::namespace('TrainingCenter')->group(function () {
             Route::resource('students', 'StudentController', ['except' => 'show']);
             Route::resource('age-categories', 'AgeCategoryController', ['except' => 'show']);
             Route::resource('origins', 'OriginController', ['except' => 'show']);
             Route::resource('guardians', 'GuardianController', ['except' => 'show']);
             Route::resource('teachers', 'TeacherController', ['except' => 'show']);
             Route::resource('bands', 'BandController', ['except' => 'show']);
             Route::resource('modalities', 'ModalityController', ['except' => 'show']);

             Route::resource('classrooms', 'ClassroomController');

             Route::prefix('classrooms')->name('classrooms.')->group(function () {
                 Route::resource('{classroom}/frequencies', 'FrequencyController');
                 Route::name('activate')->get('/activate/{classroom}', 'ClassroomController@activate');
                 Route::name('deactivate')->get('/deactivate/{classroom}', 'ClassroomController@deactivate');
             });

             Route::resource('classrooms-teachers', 'ClassroomTeacherController');

             Route::prefix('classrooms-teachers')->name('classrooms-teachers.')->group(function() {
                Route::name('add-teacher')->post('/add-teacher', 'ClassroomTeacherController@addTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
             });

             Route::name('students.')->prefix('students')->group(function () {
                 Route::name('export')->get('/export', 'StudentController@export');
                 Route::resource('attachments', 'AttachmentController', ['only' => ['show', 'update']]);

                 Route::resource('{registration}/graduations', 'GraduationController', ['except' => 'show']);
                 Route::resource('{registration}/installments', 'InstallmentController', ['except' => 'show']);
                 Route::resource('{registration}/issues', 'IssueController', ['only' => 'index']);

                 Route::name('skip-check')->post('/skip-check/{registration}', 'StudentController@skipcheck');
                 Route::name('graduations.print')->get('{registration}/print/{graduation}', 'GraduationController@print');
                 Route::name('deactivate-registration')->post('/deactivate-registration/{registration}', 'StudentController@deactivateRegistration');
                 Route::name('reactivate-registration')->get('/reactivate-registration/{registration}', 'StudentController@reactivateRegistration');
            });

            Route::name('new-registration.')->prefix('new-registration')->group(function () {
                Route::name('index')->get('/index', 'NewRegistrationController@index');
                Route::name('guardian')->get('/{student}/guardian', 'NewRegistrationController@guardian');
                Route::name('registration')->get('/{student}/registration', 'NewRegistrationController@registration');
                Route::name('financial')->get('/{student}/financial', 'NewRegistrationController@financial');
                Route::name('graduation')->get('/{student}/graduation', 'NewRegistrationController@graduation');

                Route::name('save-student')->post('/save-student', 'NewRegistrationController@saveStudent');
                Route::name('save-guardian')->post('/{student}/save-guardian', 'NewRegistrationController@saveGuardian');
                Route::name('save-registration')->post('/{student}/save-registration', 'NewRegistrationController@saveRegistration');
                Route::name('save-financial')->post('/{student}/save-financial', 'NewRegistrationController@saveFinancial');
                Route::name('save-graduation')->post('/{student}/save-graduation', 'NewRegistrationController@saveGraduation');
            });
         });

         Route::namespace('Auth')->prefix('users')->group(function () {
             Route::resource('permissions', 'PermissionController', ['except' => 'show']);
             Route::resource('roles', 'RoleController', ['except' => 'show']);

             Route::name('users.sendEmail')->get('/resend-confirmation/{user}', 'UserController@sendEmail');
             Route::name('users.activate')->get('/activate/{user}', 'UserController@activate');
             Route::name('users.deactivate')->get('/deactivate/{user}', 'UserController@deactivate');
         });

         Route::namespace('Finances')->group(function () {
             Route::resource('balance-records', 'BalanceRecordController', ['except' => 'show']);
             Route::resource('monthly-charge', 'MonthlyChargeController', ['only' => 'store']);
         });

         Route::namespace('Juno')->prefix('juno')->group(function() {
             Route::resource('transfer', 'TransferController', ['only' => ['index', 'store']]);
             Route::resource('split', 'SplitReportController', ['only' => ['index']]);
             Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'store']]);
         });

         Route::name('juno.')->prefix('juno')->group(function() {
            Route::name('cancel')->prefix('cancel')->post('/cancel/{invoice}', 'Juno\InvoiceController@cancel');
            Route::name('manual-payment')->prefix('manual-payment')->post('/manual-payment/{invoice}', 'Juno\InvoiceController@manulPayment');
        });

         Route::namespace('Reports')->group(function(){
             Route::prefix('qualifications')->name('qualifications.')->group(function() {
                 Route::name('index')->get('/', 'QualificationController@index');
                 Route::name('print')->get('/print', 'QualificationController@print');
             });

              Route::prefix('reports')->name('reports.')->group(function () {
                 Route::name('balance')->get('/balance', 'BalanceController@index');
                 Route::name('overdue')->get('/overdue', 'OverdueController@index');
                 Route::name('resend-overdues')->post('/resend-overdues', 'OverdueController@resend');
                 Route::name('class-billing')->get('/class-billing', 'BillingPerClassController@index');
                 Route::name('annual-summary')->get('/annual-summary', 'AnnualSummaryController@index');
              });
         });

         Route::resource('persons', 'PersonController', ['only' => 'show']);
         Route::resource('messages', 'MessageController');
         Route::resource('users', 'Auth\UserController', ['except' => 'show']);
         Route::resource('audits', 'AuditController', ['only' => ['index', 'show']]);
         Route::resource('subsidiaries', 'SubsidiaryController', ['except' => 'show']);

         Route::prefix('subsidiaries')->name('subsidiaries.')->group(function(){
             Route::name('documents.index')->get('{id}/documents', 'DocumentController@index');
             Route::name('documents.store')->post('{id}/documents/store', 'DocumentController@store');
         });

         Route::prefix('settings')->name('settings.')->group(function (){
             Route::name('edit')->get('/edit', 'SettingController@edit');
             Route::name('update')->put('/update', 'SettingController@update');
         });

         Route::prefix('users')->name('users.')->group(function () {
            Route::name('term')->get('/term', 'UserTermController@index');
            Route::name('accept-term')->post('/accept-term', 'UserTermController@accept');
         });
     });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest.admin')->group(function () {

    //Auto login
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    Route::namespace('Auth\Sessions')->group(function () {

        Route::get('/', 'SessionController@showLoginForm');
        Route::name('login')->get('/login', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->get('/acessar', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->post('/acessar', 'SessionController@login');

        // Reset Password
        Route::name('auth.password.forgot')->get('/esqueci-minha-senha', 'ForgotPasswordController@showLinkRequestForm');
        Route::name('auth.password.processForgot')->post('/esqueci-minha-senha', 'ForgotPasswordController@sendResetLinkEmail');
        Route::name('auth.password.reset')->get('/cadastrar-senha/{token}/{email}', 'ResetPasswordController@showResetForm');
        Route::name('auth.password.processReset')->post('/cadastrar-senha', 'ResetPasswordController@reset');

        // First access
        Route::name('auth.activation.create')->get('/primeiro-acesso/{activation}', 'ActivationController@showActivationForm');
        Route::name('auth.activation.processCreate')->post('/primeiro-acesso/{token}', 'ActivationController@store');
    });
});

// Logout
Route::middleware('auth.admin')->group(function() {
    Route::name('auth.session.logout')->get('/sair', 'Auth\Sessions\SessionController@logout');
    Route::name('core.notifications.destroy')->delete('/excluir/{notification}', 'Core\NotificationController@destroy');
    Route::name('core.notifications.read')->put('/{notification}', 'Core\NotificationController@update');
});

resources/views/admin/partials/breadcrumbs.blade.php
@if(Agent::isDesktop())
@if (count($breadcrumbs))
  <div class="section-header-breadcrumb">
    @foreach ($breadcrumbs as $breadcrumb)
      @if ($breadcrumb->url && !$loop->last)
        <div class="breadcrumb-item">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @else
        <div class="breadcrumb-item breadcrumb-active">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @endif
    @endforeach
  </div>
@endif
@endif

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
  <div class="footer-left">
    Copyright &copy; 2019
    <div class="bullet"></div> Desenvolvido e mantido por  <a href="https://qualitare.com/">Qualitare</a>
  </div>
  <div class="footer-right">
    1.0.0
  </div>
</footer>

resources/views/admin/partials/nav.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar"
                   class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

    </form>
    <ul class="navbar-nav navbar-right">

        @auth()
            @include('layouts.common._notifications')

            <li class="dropdown">
                <a href="#" data-toggle="dropdown"
                   class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                    <img alt="image" src="{{ auth()->user()->avatarUrl }}"
                         class="rounded-circle mr-1">
                    <div class="d-sm-none d-lg-inline-block">
                        Olá, {{ auth()->user()->nickname }}</div>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    @include('layouts.common._roles')
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('auth.session.logout') }}"
                       class="dropdown-item has-icon text-danger">
                        <i class="fas fa-sign-out-alt"></i> Sair
                    </a>
                </div>
            </li>
        @endauth
    </ul>
</nav>

resources/views/admin/partials/option.blade.php
@can($item['permission'])
    <li class="{{ (Route::currentRouteName() == $item['route']) ? 'active' : '' }}">
        <a class="{{ (Route::currentRouteName() == $item['route']) ? 'actived' : '' }} nav-link"
           href="{{ route($item['route']) }}"
           title="{{ $item['name'] }}">
            <i class="{{ $item['icon'] }}"></i>
            <span>{{ $item['name'] }}</span>
        </a>
    </li>
@endcan

resources/views/admin/partials/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand mb-2">
            <a href="{{ route('admin.dashboard.index') }}">
                <img src="{{ asset('img/brand.png') }}"
                     width="50"></a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('admin.dashboard.index') }}">
                <img src="{{ asset('img/brand.png') }}"
                     width="50"></a>
        </div>

        @can('registration')
            <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
                <a href="{{ route('admin.new-registration.index') }}" class="btn btn-primary btn-lg btn-block btn-icon-split">
                    <i class="fas fa-graduation-cap"></i> Nova matrícula
                </a>
            </div>
        @endcan

        <ul class="sidebar-menu mt-4">

            @foreach(config('qualitare.modules') as $module)

                @can($module['permission'])
                    <li class="menu-header">{{ $module['name'] }}</li>

                    @foreach($module['options'] as $option)

                        @can($option['permission'])

                            @if(!$option['is_tree'])
                                @include('admin.partials.option', ['item' => $option])
                            @else
                                @include('admin.partials.tree', ['tree' => $option])
                            @endif

                        @endcan

                    @endforeach

                @endcan

            @endforeach
        </ul>
    </aside>
</div>

resources/views/admin/partials/tree.blade.php
@can($tree['permission'])

    <li class="dropdown {{ activeTree($tree) ? 'active' : '' }}">
        <a href="#"
           class="nav-link has-dropdown"
           data-toggle="dropdown">
            <i class="fas {{ $tree['icon'] }}"></i>
            <span>{{ $tree['name'] }}</span>
        </a>
        <ul class="dropdown-menu"
            style="display: none;">
            @foreach($tree['options'] as $option)
                @include('admin.partials.option', ['item' => $option])
            @endforeach
        </ul>
    </li>


@endcan