routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')
     ->namespace('Admin')
     ->name('admin.')
     ->middleware(['auth.admin', 'role.check', 'first.access', 'term.check'])
     ->group(function () {

         Route::namespace('Dashboard')->group(function () {
             Route::name('dashboard.index')->get('/', 'DashboardController@index');

             Route::prefix('financial')->name('financial.')->group(function () {
                 Route::name('index')->get('/', 'FinancialController@index');
                 Route::get('/income', 'FinancialController@income');
                 Route::get('/outcome', 'FinancialController@outcome');
                 Route::get('/active-students', 'FinancialController@activeStudents');
                 Route::get('/registrations', 'FinancialController@registrations');
                 Route::get('/billing-summary', 'FinancialController@billingSummary');
                 Route::get('/billing-per-payment-type', 'FinancialController@billingPerPaymentType');
                 Route::get('/students-by-status', 'FinancialController@studentsByStatus');
             });

             Route::prefix('academic')->name('academic.')->group(function () {
                 Route::name('index')->get('/', 'AcademicController@index');
                 Route::get('/students-per-sex', 'AcademicController@studentsPerSex');
                 Route::get('/students-per-age-categories', 'AcademicController@studentsPerAgeCategories');
                 Route::get('/students-per-bands', 'AcademicController@studentsPerBands');
             });
         });

         Route::namespace('TrainingCenter')->group(function () {
             Route::resource('students', 'StudentController', ['except' => 'show']);
             Route::resource('age-categories', 'AgeCategoryController', ['except' => 'show']);
             Route::resource('origins', 'OriginController', ['except' => 'show']);
             Route::resource('guardians', 'GuardianController', ['except' => 'show']);
             Route::resource('teachers', 'TeacherController', ['except' => 'show']);
             Route::resource('bands', 'BandController', ['except' => 'show']);
             Route::resource('modalities', 'ModalityController', ['except' => 'show']);

             Route::resource('classrooms', 'ClassroomController');

             Route::prefix('classrooms')->name('classrooms.')->group(function () {
                 Route::resource('{classroom}/frequencies', 'FrequencyController');
                 Route::name('activate')->get('/activate/{classroom}', 'ClassroomController@activate');
                 Route::name('deactivate')->get('/deactivate/{classroom}', 'ClassroomController@deactivate');
             });

             Route::resource('classrooms-teachers', 'ClassroomTeacherController');

             Route::prefix('classrooms-teachers')->name('classrooms-teachers.')->group(function() {
                Route::name('add-teacher')->post('/add-teacher', 'ClassroomTeacherController@addTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
                Route::name('remove-teacher')->post('/remove-teacher', 'ClassroomTeacherController@removeTeacher');
             });

             Route::name('students.')->prefix('students')->group(function () {
                 Route::name('export')->get('/export', 'StudentController@export');
                 Route::resource('attachments', 'AttachmentController', ['only' => ['show', 'update']]);

                 Route::resource('{registration}/graduations', 'GraduationController', ['except' => 'show']);
                 Route::resource('{registration}/installments', 'InstallmentController', ['except' => 'show']);
                 Route::resource('{registration}/issues', 'IssueController', ['only' => 'index']);

                 Route::name('skip-check')->post('/skip-check/{registration}', 'StudentController@skipcheck');
                 Route::name('graduations.print')->get('{registration}/print/{graduation}', 'GraduationController@print');
                 Route::name('deactivate-registration')->post('/deactivate-registration/{registration}', 'StudentController@deactivateRegistration');
                 Route::name('reactivate-registration')->get('/reactivate-registration/{registration}', 'StudentController@reactivateRegistration');
            });

            Route::name('new-registration.')->prefix('new-registration')->group(function () {
                Route::name('index')->get('/index', 'NewRegistrationController@index');
                Route::name('guardian')->get('/{student}/guardian', 'NewRegistrationController@guardian');
                Route::name('registration')->get('/{student}/registration', 'NewRegistrationController@registration');
                Route::name('financial')->get('/{student}/financial', 'NewRegistrationController@financial');
                Route::name('graduation')->get('/{student}/graduation', 'NewRegistrationController@graduation');

                Route::name('save-student')->post('/save-student', 'NewRegistrationController@saveStudent');
                Route::name('save-guardian')->post('/{student}/save-guardian', 'NewRegistrationController@saveGuardian');
                Route::name('save-registration')->post('/{student}/save-registration', 'NewRegistrationController@saveRegistration');
                Route::name('save-financial')->post('/{student}/save-financial', 'NewRegistrationController@saveFinancial');
                Route::name('save-graduation')->post('/{student}/save-graduation', 'NewRegistrationController@saveGraduation');
            });
         });

         Route::namespace('Auth')->prefix('users')->group(function () {
             Route::resource('permissions', 'PermissionController', ['except' => 'show']);
             Route::resource('roles', 'RoleController', ['except' => 'show']);

             Route::name('users.sendEmail')->get('/resend-confirmation/{user}', 'UserController@sendEmail');
             Route::name('users.activate')->get('/activate/{user}', 'UserController@activate');
             Route::name('users.deactivate')->get('/deactivate/{user}', 'UserController@deactivate');
         });

         Route::namespace('Finances')->group(function () {
             Route::resource('balance-records', 'BalanceRecordController', ['except' => 'show']);
             Route::resource('monthly-charge', 'MonthlyChargeController', ['only' => 'store']);
         });

         Route::namespace('Juno')->prefix('juno')->group(function() {
             Route::resource('transfer', 'TransferController', ['only' => ['index', 'store']]);
             Route::resource('split', 'SplitReportController', ['only' => ['index']]);
             Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'store']]);
         });

         Route::name('juno.')->prefix('juno')->group(function() {
            Route::name('cancel')->prefix('cancel')->post('/cancel/{invoice}', 'Juno\InvoiceController@cancel');
            Route::name('manual-payment')->prefix('manual-payment')->post('/manual-payment/{invoice}', 'Juno\InvoiceController@manulPayment');
        });

         Route::namespace('Reports')->group(function(){
             Route::prefix('qualifications')->name('qualifications.')->group(function() {
                 Route::name('index')->get('/', 'QualificationController@index');
                 Route::name('print')->get('/print', 'QualificationController@print');
             });

              Route::prefix('reports')->name('reports.')->group(function () {
                 Route::name('balance')->get('/balance', 'BalanceController@index');
                 Route::name('overdue')->get('/overdue', 'OverdueController@index');
                 Route::name('resend-overdues')->post('/resend-overdues', 'OverdueController@resend');
                 Route::name('class-billing')->get('/class-billing', 'BillingPerClassController@index');
                 Route::name('annual-summary')->get('/annual-summary', 'AnnualSummaryController@index');
              });
         });

         Route::resource('persons', 'PersonController', ['only' => 'show']);
         Route::resource('messages', 'MessageController');
         Route::resource('users', 'Auth\UserController', ['except' => 'show']);
         Route::resource('audits', 'AuditController', ['only' => ['index', 'show']]);
         Route::resource('subsidiaries', 'SubsidiaryController', ['except' => 'show']);

         Route::prefix('subsidiaries')->name('subsidiaries.')->group(function(){
             Route::name('documents.index')->get('{id}/documents', 'DocumentController@index');
             Route::name('documents.store')->post('{id}/documents/store', 'DocumentController@store');
         });

         Route::prefix('settings')->name('settings.')->group(function (){
             Route::name('edit')->get('/edit', 'SettingController@edit');
             Route::name('update')->put('/update', 'SettingController@update');
         });

         Route::prefix('users')->name('users.')->group(function () {
            Route::name('term')->get('/term', 'UserTermController@index');
            Route::name('accept-term')->post('/accept-term', 'UserTermController@accept');
         });
     });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest.admin')->group(function () {

    //Auto login
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    Route::namespace('Auth\Sessions')->group(function () {

        Route::get('/', 'SessionController@showLoginForm');
        Route::name('login')->get('/login', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->get('/acessar', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->post('/acessar', 'SessionController@login');

        // Reset Password
        Route::name('auth.password.forgot')->get('/esqueci-minha-senha', 'ForgotPasswordController@showLinkRequestForm');
        Route::name('auth.password.processForgot')->post('/esqueci-minha-senha', 'ForgotPasswordController@sendResetLinkEmail');
        Route::name('auth.password.reset')->get('/cadastrar-senha/{token}/{email}', 'ResetPasswordController@showResetForm');
        Route::name('auth.password.processReset')->post('/cadastrar-senha', 'ResetPasswordController@reset');

        // First access
        Route::name('auth.activation.create')->get('/primeiro-acesso/{activation}', 'ActivationController@showActivationForm');
        Route::name('auth.activation.processCreate')->post('/primeiro-acesso/{token}', 'ActivationController@store');
    });
});

// Logout
Route::middleware('auth.admin')->group(function() {
    Route::name('auth.session.logout')->get('/sair', 'Auth\Sessions\SessionController@logout');
    Route::name('core.notifications.destroy')->delete('/excluir/{notification}', 'Core\NotificationController@destroy');
    Route::name('core.notifications.read')->put('/{notification}', 'Core\NotificationController@update');
});

app/Http/Controllers/Admin/DocumentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Core\Services\Juno\DocumentService;
use App\Core\Services\SubsidiaryService;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DocumentController extends Controller
{
    use SEOToolsTrait;

    protected DocumentService   $service;
    protected SubsidiaryService $subsidiaryService;

    /**
     * DocumentController constructor.
     *
     * @param \App\Core\Services\Juno\DocumentService $service
     * @param \App\Core\Services\SubsidiaryService $subsidiaryService
     */
    public function __construct(DocumentService $service, SubsidiaryService $subsidiaryService)
    {
        $this->seo()->setTitle('Documentos');

        $this->middleware('permission:view_subsidiaries', ['only' => ['index']]);
        $this->middleware('permission:add_subsidiaries', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit_subsidiaries', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete_subsidiaries', ['only' => ['destroy']]);

        $this->service           = $service;
        $this->subsidiaryService = $subsidiaryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index(int $id)
    {
        $subsidiary = $this->subsidiaryService->find($id);
        $results    = $this->service->list($subsidiary)->documents;

        return view('admin.subsidiaries.documents.index',
            compact('results', 'subsidiary')
        );
    }

    public function store(Request $request, int $id)
    {
        $subsidiary = $this->subsidiaryService->find($id);
        $this->service->send(
            $subsidiary,
            $request->file('document'),
            $request->get('document_id'));

        toast()->success('Documento enviado com sucesso.', 'Sucesso');

        return redirect()->route('admin.subsidiaries.documents.index', ['id' => $id]);
    }


}

resources/views/admin/subsidiaries/documents/index.blade.php
@extends('layouts.default')

@section('content')

    <section class="section">
        <div class="section-header mb-3">
            <div class="section-header-back">
                <a href="{{ route('admin.subsidiaries.index') }}"
                   class="btn btn-icon"
                   title="Voltar">
                    <i class="fas fa-arrow-left"></i>
                </a>
            </div>
            <h1>Documentos</h1>
            {!! Breadcrumbs::render('subsidiaries.index') !!}
        </div>

        <div class="section-body mt-4">
            <div class="row mt-4">
                <div class="col-lg-12 col-sm-12">
                    <h6 class="mb-3">Listagem de documentos necessários</h6>
                    <div class="card">
                        <div class="card-body -table mb-0">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover overflow mb-0">
                                    <tbody>
                                        <tr class="tr-a">
                                            <th>Descrição</th>
                                            <th>Status</th>
                                        </tr>
                                        @foreach($results as $result)
                                            <tr class="tr-item td-border hover-click"
                                                onclick="{{ $result->approvalStatus != 'VERIFYING' ? 'openModal(this)' : ''  }}"
                                                data-link="{{ route('admin.subsidiaries.documents.store', ['id' => $subsidiary->id]) }}"
                                                data-document="{{ $result->id }}">
                                                <td class="td-item">{{ $result->description }}</td>
                                                <td class="td-item">{{ $result->approvalStatus }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade"
             tabindex="-1"
             role="dialog"
             id="documentModal">
            <div class="modal-dialog modal-dialog-centered"
                 role="document">
                <div class="modal-content">
                    {!! Form::open(['method' => 'POST', 'novalidate', 'role' => 'form', 'class' => 'form', 'enctype' => 'multipart/form-data', 'id' => 'document-form']) !!}
                    <div class="modal-header">
                        <h5 class="modal-title">Enviar documento</h5>
                        <button type="button"
                                class="close"
                                data-dismiss="modal"
                                aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row border p-4">
                            {{ Form::file('document', ['required' => true]) }}
                            {{ Form::hidden('document_id') }}
                        </div>
                    </div>
                    <div class="modal-footer bg-whitesmoke br">
                        <button type="button"
                                class="btn btn-secondary"
                                data-dismiss="modal">Cancelar
                        </button>
                        <button type="submit"
                                class="btn btn-success">Enviar
                        </button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script>
        function openModal(element) {
            let action = $(element).data('link');
            let document = $(element).data('document');

            $('input[name="document_id"]').val(document);
            $('form#document-form').attr('action', action);

            $('#documentModal').modal('toggle');
        }
    </script>
@endpush